he <-data.frame(name = c("mol"),stringsAsFactors=FALSE)
rmsd <- read.table("rmsd.xvg", strip.white = TRUE, skip=18, head=FALSE)
enrg1 <- read.table("enrg1.xvg", strip.white = TRUE, skip=24, head=FALSE)
enrg2 <- read.table("enrg2.xvg", strip.white = TRUE, skip=24, head=FALSE)
enrg3 <- read.table("enrg3.xvg", strip.white = TRUE, skip=24, head=FALSE)
enrg5 <- read.table("enrg5.xvg", strip.white = TRUE, skip=24, head=FALSE)
enrg6 <- read.table("enrg6.xvg", strip.white = TRUE, skip=24, head=FALSE)
enrg7 <- read.table("enrg7.xvg", strip.white = TRUE, skip=24, head=FALSE)
enrg8 <- read.table("enrg8.xvg", strip.white = TRUE, skip=24, head=FALSE)
enrg9 <- read.table("enrg9.xvg", strip.white = TRUE, skip=24, head=FALSE)
enrg10 <- read.table("enrg10.xvg", strip.white = TRUE, skip=24, head=FALSE)
enrg11 <- read.table("enrg11.xvg", strip.white = TRUE, skip=24, head=FALSE)
enrg12 <- read.table("enrg12.xvg", strip.white = TRUE, skip=24, head=FALSE)
enrg13 <- read.table("enrg13.xvg", strip.white = TRUE, skip=24, head=FALSE)
enrg14 <- read.table("enrg14.xvg", strip.white = TRUE, skip=24, head=FALSE)
enrg15 <- read.table("enrg15.xvg", strip.white = TRUE, skip=24, head=FALSE)
enrg16 <- read.table("enrg16.xvg", strip.white = TRUE, skip=24, head=FALSE)
enrg17 <- read.table("enrg17.xvg", strip.white = TRUE, skip=24, head=FALSE)
enrg18 <- read.table("enrg18.xvg", strip.white = TRUE, skip=24, head=FALSE)
enrg19 <- read.table("enrg19.xvg", strip.white = TRUE, skip=24, head=FALSE)
enrg20 <- read.table("enrg20.xvg", strip.white = TRUE, skip=24, head=FALSE)
enrg21 <- read.table("enrg21.xvg", strip.white = TRUE, skip=24, head=FALSE)
enrg22 <- read.table("enrg22.xvg", strip.white = TRUE, skip=24, head=FALSE)
enrg23 <- read.table("enrg23.xvg", strip.white = TRUE, skip=24, head=FALSE)
enrg24 <- read.table("enrg24.xvg", strip.white = TRUE, skip=24, head=FALSE)
enrg25 <- read.table("enrg25.xvg", strip.white = TRUE, skip=24, head=FALSE)
enrg26 <- read.table("enrg26.xvg", strip.white = TRUE, skip=24, head=FALSE)
enrg27 <- read.table("enrg27.xvg", strip.white = TRUE, skip=24, head=FALSE)
enrg28 <- read.table("enrg28.xvg", strip.white = TRUE, skip=24, head=FALSE)
enrg29 <- read.table("enrg29.xvg", strip.white = TRUE, skip=24, head=FALSE)
enrg30 <- read.table("enrg30.xvg", strip.white = TRUE, skip=24, head=FALSE)
enrg31 <- read.table("enrg31.xvg", strip.white = TRUE, skip=24, head=FALSE)
enrg32 <- read.table("enrg32.xvg", strip.white = TRUE, skip=24, head=FALSE)
enrg33 <- read.table("enrg33.xvg", strip.white = TRUE, skip=24, head=FALSE)
enrg34 <- read.table("enrg34.xvg", strip.white = TRUE, skip=24, head=FALSE)
enrg35 <- read.table("enrg35.xvg", strip.white = TRUE, skip=24, head=FALSE)
enrg36 <- read.table("enrg36.xvg", strip.white = TRUE, skip=24, head=FALSE)
enrg37 <- read.table("enrg37.xvg", strip.white = TRUE, skip=24, head=FALSE)
enrg38 <- read.table("enrg38.xvg", strip.white = TRUE, skip=24, head=FALSE)
enrg39 <- read.table("enrg39.xvg", strip.white = TRUE, skip=24, head=FALSE)
enrg40 <- read.table("enrg40.xvg", strip.white = TRUE, skip=24, head=FALSE)
enrg41 <- read.table("enrg41.xvg", strip.white = TRUE, skip=24, head=FALSE)
enrg42 <- read.table("enrg42.xvg", strip.white = TRUE, skip=24, head=FALSE)
enrg43 <- read.table("enrg43.xvg", strip.white = TRUE, skip=24, head=FALSE)
enrg44 <- read.table("enrg44.xvg", strip.white = TRUE, skip=24, head=FALSE)
enrg45 <- read.table("enrg45.xvg", strip.white = TRUE, skip=24, head=FALSE)
enrg46 <- read.table("enrg46.xvg", strip.white = TRUE, skip=24, head=FALSE)
enrg47 <- read.table("enrg47.xvg", strip.white = TRUE, skip=24, head=FALSE)
fhnum <- read.table("fws_hnum.xvg", strip.white = TRUE, skip=25, head=FALSE)
fgyr <- read.table("fws-gyrate.xvg", strip.white = TRUE, skip=27, head=FALSE)
area <- read.table("area.xvg", strip.white = TRUE, skip=24, head=FALSE)

he$"rmsd-sd" <- sd(rmsd$V2)
he$"rmsd-avg" <- mean(rmsd$V2)
he$"rmsd-mid" <- median(rmsd$V2)
he$"enrg1-sd" <- sd(enrg1$V2)
he$"enrg1-avg" <- mean(enrg1$V2)
he$"enrg1-mid" <- median(enrg1$V2)
he$"enrg2-sd" <- sd(enrg2$V2)
he$"enrg2-avg" <- mean(enrg2$V2)
he$"enrg2-mid" <- median(enrg2$V2)
he$"enrg3-sd" <- sd(enrg3$V2)
he$"enrg3-avg" <- mean(enrg3$V2)
he$"enrg3-mid" <- median(enrg3$V2)
he$"enrg5-sd" <- sd(enrg5$V2)
he$"enrg5-avg" <- mean(enrg5$V2)
he$"enrg5-mid" <- median(enrg5$V2)
he$"enrg6-sd" <- sd(enrg6$V2)
he$"enrg6-avg" <- mean(enrg6$V2)
he$"enrg6-mid" <- median(enrg6$V2)
he$"enrg7-sd" <- sd(enrg7$V2)
he$"enrg7-avg" <- mean(enrg7$V2)
he$"enrg7-mid" <- median(enrg7$V2)
he$"enrg8-sd" <- sd(enrg8$V2)
he$"enrg8-avg" <- mean(enrg8$V2)
he$"enrg8-mid" <- median(enrg8$V2)
he$"enrg9-sd" <- sd(enrg9$V2)
he$"enrg9-avg" <- mean(enrg9$V2)
he$"enrg9-mid" <- median(enrg9$V2)
he$"enrg10-sd" <- sd(enrg10$V2)
he$"enrg10-avg" <- mean(enrg10$V2)
he$"enrg10-mid" <- median(enrg10$V2)
he$"enrg11-sd" <- sd(enrg11$V2)
he$"enrg11-avg" <- mean(enrg11$V2)
he$"enrg11-mid" <- median(enrg11$V2)
he$"enrg12-sd" <- sd(enrg12$V2)
he$"enrg12-avg" <- mean(enrg12$V2)
he$"enrg12-mid" <- median(enrg12$V2)
he$"enrg13-sd" <- sd(enrg13$V2)
he$"enrg13-avg" <- mean(enrg13$V2)
he$"enrg13-mid" <- median(enrg13$V2)
he$"enrg14-sd" <- sd(enrg14$V2)
he$"enrg14-avg" <- mean(enrg14$V2)
he$"enrg14-mid" <- median(enrg14$V2)
he$"enrg15-sd" <- sd(enrg15$V2)
he$"enrg15-avg" <- mean(enrg15$V2)
he$"enrg15-mid" <- median(enrg15$V2)
he$"enrg16-sd" <- sd(enrg16$V2)
he$"enrg16-avg" <- mean(enrg16$V2)
he$"enrg16-mid" <- median(enrg16$V2)
he$"enrg17-sd" <- sd(enrg17$V2)
he$"enrg17-avg" <- mean(enrg17$V2)
he$"enrg17-mid" <- median(enrg17$V2)
he$"enrg18-sd" <- sd(enrg18$V2)
he$"enrg18-avg" <- mean(enrg18$V2)
he$"enrg18-mid" <- median(enrg18$V2)
he$"enrg19-sd" <- sd(enrg19$V2)
he$"enrg19-avg" <- mean(enrg19$V2)
he$"enrg19-mid" <- median(enrg19$V2)
he$"enrg20-sd" <- sd(enrg20$V2)
he$"enrg20-avg" <- mean(enrg20$V2)
he$"enrg20-mid" <- median(enrg20$V2)
he$"enrg21-sd" <- sd(enrg21$V2)
he$"enrg21-avg" <- mean(enrg21$V2)
he$"enrg21-mid" <- median(enrg21$V2)
he$"enrg22-sd" <- sd(enrg22$V2)
he$"enrg22-avg" <- mean(enrg22$V2)
he$"enrg22-mid" <- median(enrg22$V2)
he$"enrg23-sd" <- sd(enrg23$V2)
he$"enrg23-avg" <- mean(enrg23$V2)
he$"enrg23-mid" <- median(enrg23$V2)
he$"enrg24-sd" <- sd(enrg24$V2)
he$"enrg24-avg" <- mean(enrg24$V2)
he$"enrg24-mid" <- median(enrg24$V2)
he$"enrg25-sd" <- sd(enrg25$V2)
he$"enrg25-avg" <- mean(enrg25$V2)
he$"enrg25-mid" <- median(enrg25$V2)
he$"enrg26-sd" <- sd(enrg26$V2)
he$"enrg26-avg" <- mean(enrg26$V2)
he$"enrg26-mid" <- median(enrg26$V2)
he$"enrg27-sd" <- sd(enrg27$V2)
he$"enrg27-avg" <- mean(enrg27$V2)
he$"enrg27-mid" <- median(enrg27$V2)
he$"enrg28-sd" <- sd(enrg28$V2)
he$"enrg28-avg" <- mean(enrg28$V2)
he$"enrg28-mid" <- median(enrg28$V2)
he$"enrg29-sd" <- sd(enrg29$V2)
he$"enrg29-avg" <- mean(enrg29$V2)
he$"enrg29-mid" <- median(enrg29$V2)
he$"enrg30-sd" <- sd(enrg30$V2)
he$"enrg30-avg" <- mean(enrg30$V2)
he$"enrg30-mid" <- median(enrg30$V2)
he$"enrg31-sd" <- sd(enrg31$V2)
he$"enrg31-avg" <- mean(enrg31$V2)
he$"enrg31-mid" <- median(enrg31$V2)
he$"enrg32-sd" <- sd(enrg32$V2)
he$"enrg32-avg" <- mean(enrg32$V2)
he$"enrg32-mid" <- median(enrg32$V2)
he$"enrg33-sd" <- sd(enrg33$V2)
he$"enrg33-avg" <- mean(enrg33$V2)
he$"enrg33-mid" <- median(enrg33$V2)
he$"enrg34-sd" <- sd(enrg34$V2)
he$"enrg34-avg" <- mean(enrg34$V2)
he$"enrg34-mid" <- median(enrg34$V2)
he$"enrg35-sd" <- sd(enrg35$V2)
he$"enrg35-avg" <- mean(enrg35$V2)
he$"enrg35-mid" <- median(enrg35$V2)
he$"enrg36-sd" <- sd(enrg36$V2)
he$"enrg36-avg" <- mean(enrg36$V2)
he$"enrg36-mid" <- median(enrg36$V2)
he$"enrg37-sd" <- sd(enrg37$V2)
he$"enrg37-avg" <- mean(enrg37$V2)
he$"enrg37-mid" <- median(enrg37$V2)
he$"enrg38-sd" <- sd(enrg38$V2)
he$"enrg38-avg" <- mean(enrg38$V2)
he$"enrg38-mid" <- median(enrg38$V2)
he$"enrg39-sd" <- sd(enrg39$V2)
he$"enrg39-avg" <- mean(enrg39$V2)
he$"enrg39-mid" <- median(enrg39$V2)
he$"enrg40-sd" <- sd(enrg40$V2)
he$"enrg40-avg" <- mean(enrg40$V2)
he$"enrg40-mid" <- median(enrg40$V2)
he$"enrg41-sd" <- sd(enrg41$V2)
he$"enrg41-avg" <- mean(enrg41$V2)
he$"enrg41-mid" <- median(enrg41$V2)
he$"enrg42-sd" <- sd(enrg42$V2)
he$"enrg42-avg" <- mean(enrg42$V2)
he$"enrg42-mid" <- median(enrg42$V2)
he$"enrg43-sd" <- sd(enrg43$V2)
he$"enrg43-avg" <- mean(enrg43$V2)
he$"enrg43-mid" <- median(enrg43$V2)
he$"enrg44-sd" <- sd(enrg44$V2)
he$"enrg44-avg" <- mean(enrg44$V2)
he$"enrg44-mid" <- median(enrg44$V2)
he$"enrg45-sd" <- sd(enrg45$V2)
he$"enrg45-avg" <- mean(enrg45$V2)
he$"enrg45-mid" <- median(enrg45$V2)
he$"enrg46-sd" <- sd(enrg46$V2)
he$"enrg46-avg" <- mean(enrg46$V2)
he$"enrg46-mid" <- median(enrg46$V2)
he$"enrg47-sd" <- sd(enrg47$V2)
he$"enrg47-avg" <- mean(enrg47$V2)
he$"enrg47-mid" <- median(enrg47$V2)
he$"fhnum-sd" <- sd(fhnum$V2)
he$"fhnum-avg" <- mean(fhnum$V2)
he$"fhnum-mid" <- median(fhnum$V2)
he$"fhnum1-sd" <- sd(fhnum$V3)
he$"fhnum1-avg" <- mean(fhnum$V3)
he$"fhnum1-mid" <- median(fhnum$V3)
he$"fgyr-sd" <- sd(fgyr$V2)
he$"fgyr-avg" <- mean(fgyr$V2)
he$"fgyr-mid" <- median(fgyr$V2)
he$"fgyrx-sd" <- sd(fgyr$V3)
he$"fgyrx-avg" <- mean(fgyr$V3)
he$"fgyrx-mid" <- median(fgyr$V3)
he$"fgyry-sd" <- sd(fgyr$V4)
he$"fgyry-avg" <- mean(fgyr$V4)
he$"fgyry-mid" <- median(fgyr$V4)
he$"fgyrz-sd" <- sd(fgyr$V5)
he$"fgyrz-avg" <- mean(fgyr$V5)
he$"fgyrz-mid" <- median(fgyr$V5)
he$"area-sd" <- sd(area$V2)
he$"area-avg" <- mean(area$V2)
he$"area-mid" <- median(area$V2)
write.table(he,"he.csv",row.names=FALSE,col.names=FALSE)

q()